### ISSUE TITLE
comment.submission is not loaded or awaitable.

### ISSUE THREAD

**Issue by jackodsteel** [praw-dev/asyncpraw#12] opened 2020-09-05 12:21 UTC
**Describe the bug**

When calling `comment.submission.title`, an AttributeError is thrown due to it not being fetched.

**To Reproduce**
1. Get a comment, for example `comment = await reddit.comment("dkk4qjd")`
2. Try to get a field from the comments subreddit field, e.g. `print(comment.submission.title`
3. Observe AttibuteError: `AttributeError: 'Submission' object has no attribute 'title'. 'Submission' object has not been fetched, did you forget to execute '.load()'?`

**Expected behavior**
I would expect either the Submission object to be loaded, the Comment object return a coroutine that loads the Submission, or the `submission.title` call to be awaitable.

Maybe this is expected behaviour, but it feels a little off to have to manually call the `.load()`.

Maybe it's just because the Comment API returns enough data, but it's strange that I can do `comment.author.name` but not `comment.submission.title`.

Even if this is working as intended, it would be nice to document this on the Comment doc to say that the `submission` attribute must be manually loaded to make it clear this is expected.

**Comment by LilSpazJoekp** [comment] 2020-09-05 20:36
This is expected behavior. The `author`, `submission`, and `subreddit` attributes are lazily loaded.

> I would expect either the Submission object to be loaded, the Comment object return a coroutine that loads the Submission, or the submission.title call to be awaitable.

It is not loaded to save the additional request. When the `Comment` object is initialized, it is done so synchronously. What I mean by that is it gets the data asynchronously then initializes the object synchronously and lazily initializes the author and submission objects the same way PRAW does. Since PRAW doesn't preemptively request the author and submission data from the API I felt that Async PRAW should do the same.

> the submission.title call to be awaitable.

This would require a major restructuring of the codebase as that would require making the `.__getattr__()` method asynchronous. As a result, this would require the following code:

```python
comment = await reddit.comment("dkk4qjd")
await comment.author.load()
print(comment.author.fullname)
```

to be rewritten like so because **every** time you access an attribute it *could* make a request:

```python
comment = await reddit.comment("dkk4qjd")
author = await comment.author
print(await author.fullname)
```

> Maybe this is expected behaviour, but it feels a little off to have to manually call the .load().

Returning `.submission` as a coroutine would require the same amount of code:

- Currently:

    ```python
    comment = await reddit.comment("dkk4qjd")
    await comment.submission.load() # this fully loads the submission and only needs to be called once
    print(comment.submission.title)
    ```

- Versus it being returned as a coroutine:
    ```python
    comment = await reddit.comment("dkk4qjd")
    submission = await comment.submission
    print(submission.title)
    ```
    The downside to this is that everytime you access the `.submission` attribute on the comment it would have to awaited and set to a variable to be able to access its attributes. This would also require reworking the `Comment` and `CommentForrest` classes.

> Maybe it's just because the Comment API returns enough data, but it's strange that I can do comment.author.name but not comment.submission.title.

That is correct. The API only returns the submission's ID. Whereas the `author.name` attribute is provided by the API and is loaded into a `Redditor` object like so:

https://github.com/praw-dev/asyncpraw/blob/fb311fc33afa399834666ca18c95ec9337ba4970/asyncpraw/models/reddit/comment.py#L188-L190

 The `Redditor` object for the `.author` attribute is still lazily loaded but since `author.name` is already set it doesn't require `.load()` to be executed. However, if you were to access `author.fullname` it would return the above error.

Overall, I see three solutions to this:

1. Update the documentation to reflect the need to use run `.load()` on the lazily loaded attributes.
2. Preemptively load the `author`, `submission`, and `subreddit` attributes. This would mean that `comment = await reddit.comment("dkk4qjd")` would require 4 requests to initialize it:
   1. Fetching the comment data
   2. Fetching the author
   3. Fetching the submission
   4. Fetching the subreddit
3. Return coroutines for the `author`, `submission`, and `subreddit` attributes that can be awaited by when needed. The issue with this is that it is effectively the same amount of code as running `.load()` on each attribute as shown above.

Personally, I feel the first option is the best solution as the others would require many changes and would make Async PRAW be significantly different from how PRAW operates.

**Comment by LilSpazJoekp** [comment] 2021-01-18 01:49
I'm going to close this issue since it hasn't had any activity in 4 months. If you have anything you'd like to add feel free to do so. Thanks!

**Closed by LilSpazJoekp** 2021-01-18 01:49 UTC

**Comment by nickatnight** [comment] 2021-07-06 18:49
@LilSpazJoekp beautiful explanation, thank you
